### ISSUE TITLE
Null value returned from .GetTimeOffPolicies()

### ISSUE THREAD

**Issue by zzzaJ** [jbubriski/bamboo-hr-dotnet-client#1]
When I run the following code:

`var bhc = new BambooHrClient.BambooHrClient();`
`var timeoffpolicies = await bhc.GetTimeOffPolicies();`

I get the following error:

An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in mscorlib.dll but was not handled in user code.
Error converting value {null} to type 'System.DateTime'. Path '[0].effectiveDate', line 1, position 85.

I have not written any code using Newtonsoft and have tested other methods using the wrapper and they have all worked 100%. Thus I believe it could be an issue with the wrapper.

**Comment by jbubriski** [comment]
It sounds like EffectiveDate is just coming back as `null`.  I updated the model so that Effectivate is now `DateTime?`.  Relevant commit: https://github.com/jbubriski/bamboo-hr-dotnet-client/commit/92ac599c25351a98110d3acfb0cc99a630c54fbb

Let me know how it goes!

**Comment by zzzaJ** [comment]
Thanks a lot for fixing the issue, it's all working perfectly now.

Appreciate the good work, keep it up!
